# Generated by Django 4.0.3 on 2023-03-24 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='recipe_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe'),
        ),
    ]
